# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2010 - 2022 Intel Corporation.

obj-$(CONFIG_VIDEO_LM3643) += lm3643.o
obj-$(CONFIG_VIDEO_DW9714) += dw9714.o
obj-$(CONFIG_VIDEO_GT9769_VCM) += gt9769-vcm.o
obj-$(CONFIG_VIDEO_BU64295) += bu64295.o
obj-$(CONFIG_VIDEO_AD5816G) += ad5816g.o
obj-$(CONFIG_VIDEO_VCM_STUB) += vcm_stub.o
obj-$(CONFIG_VIDEO_OV01A1S) += ov01a1s.o
obj-$(CONFIG_VIDEO_OV01A10) += ov01a10.o
obj-$(CONFIG_VIDEO_OV02C10) += ov02c10.o
obj-$(CONFIG_VIDEO_OV8856) += ov8856.o
obj-$(CONFIG_VIDEO_OV13858_INTEL) += ov13858_intel.o
obj-$(CONFIG_VIDEO_AR0234) += ar0234.o
obj-$(CONFIG_VIDEO_HM11B1) += hm11b1.o
obj-$(CONFIG_VIDEO_IMX355) += imx355.o
obj-$(CONFIG_VIDEO_IMX319) += imx319.o
obj-$(CONFIG_VIDEO_AK7375) += ak7375.o
obj-$(CONFIG_VIDEO_MAX9286) += max9286.o
ti960-objs      :=      ti953-ser.o ti960-des.o
obj-$(CONFIG_VIDEO_TI960) += ti960.o
obj-$(CONFIG_VIDEO_OV9734) += ov9734.o
obj-$(CONFIG_POWER_CTRL_LOGIC) += power_ctrl_logic.o
obj-$(CONFIG_VIDEO_IMX390) += imx390.o
obj-$(CONFIG_VIDEO_LT6911UXC) += lt6911uxc.o
