# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021 Intel Corporation.

obj-$(CONFIG_VIDEO_HM11B1) += hm11b1.o
obj-$(CONFIG_VIDEO_OV01A1S) += ov01a1s.o
obj-$(CONFIG_POWER_CTRL_LOGIC) += power_ctrl_logic.o
